/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelos.Vehiculo;
import javax.swing.JOptionPane;

/**
 *
 * @author G
 */
public class MostrarUno extends javax.swing.JInternalFrame {

    /**
     * Creates new form MostrarUno
     */
    public MostrarUno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtPatente = new javax.swing.JTextField();
        lblPatente = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblCPatente = new javax.swing.JLabel();
        lblCMarca = new javax.swing.JLabel();
        lblCModelo = new javax.swing.JLabel();
        lblCColor = new javax.swing.JLabel();
        lblCAno = new javax.swing.JLabel();
        lblCPrecio = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Buscar Vehiculo");

        lblTitulo.setText("Ingrese Patente a buscar:");

        lblPatente.setText("Patente:");

        lblMarca.setText("Marca:");

        lblModelo.setText("Modelo:");

        lblColor.setText("Color:");

        lblAno.setText("Año:");

        lblPrecio.setText("Precio:");

        lblCPatente.setText("           ");

        lblCMarca.setText("           ");

        lblCModelo.setText("           ");

        lblCColor.setText("           ");

        lblCAno.setText("           ");

        lblCPrecio.setText("           ");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPatente)
                            .addComponent(lblMarca)
                            .addComponent(lblModelo)
                            .addComponent(lblColor)
                            .addComponent(lblAno)
                            .addComponent(lblPrecio)
                            .addComponent(btnAceptar))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCPrecio)
                            .addComponent(lblCAno)
                            .addComponent(lblCColor)
                            .addComponent(lblCModelo)
                            .addComponent(lblCMarca)
                            .addComponent(lblCPatente)
                            .addComponent(btnSalir)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(txtPatente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(txtPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatente)
                    .addComponent(lblCPatente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(lblCMarca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(lblCModelo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColor)
                    .addComponent(lblCColor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAno)
                    .addComponent(lblCAno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(lblCPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnAceptar))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String patente = txtPatente.getText();
        if(patente.equals("")||patente==null)
        {
            JOptionPane.showMessageDialog(this, "Ingrese patente");
        }
        else
        {
        Vehiculo v=new Vehiculo(patente);
        Vehiculo ve=v.buscaUno(v);
        if(ve==null)
        {
            JOptionPane.showMessageDialog(this, "Vehiculo no encontrado");
        }
        else
        {
        lblCPatente.setText(ve.getPatente());
        lblCMarca.setText(ve.getMarca());
        lblCModelo.setText(ve.getModelo());
        lblCColor.setText(ve.getColor());
        lblCAno.setText(String.valueOf(ve.getAno()));
        lblCPrecio.setText(String.valueOf(ve.getPrecio()));
        }
        }
        
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblCAno;
    private javax.swing.JLabel lblCColor;
    private javax.swing.JLabel lblCMarca;
    private javax.swing.JLabel lblCModelo;
    private javax.swing.JLabel lblCPatente;
    private javax.swing.JLabel lblCPrecio;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPatente;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtPatente;
    // End of variables declaration//GEN-END:variables
}
